[project]
name = "poliquery"
version = "0.1.0"
dependencies = ['pandas>=2.1.1', 'gql==3.5.0', 'aiohttp', 'requests']

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true