[project]
name = "politigraph-automation"
version = "1.1.0"
description = "Automation tools for WeVis politigraph project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiocache>=0.12.3",
    "aiohttp>=3.14.3",
    "beautifulsoup4>=4.15.0",
    "cachetools>=7.2.0",
    "gql>=4.0.0",
    "lxml>=6.1.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "poliquery",
    "python-dotenv>=1.2.3",
    "rapidfuzz>=3.14.6",
    "requests>=2.34.2",
    "thai-name-normalizer",
    "tqdm>=4.70.1",
]

[dependency-groups]
vote_event_scraper = [
    "pymupdf>=1.28.2",
    "opencv-python>=5.0.0.93",
    "easyocr>=1.7.2",
    "typhoon-ocr>=0.4.1",
    "msbis-vote-events-scraper",
    "vote-doc-reader",
    "vote-log-manager",
]
bills_scraper = [
    "lis-bills-scraper",
    "merge-bill-updater",
]

[tool.uv]
package = false

[tool.uv.sources]
thai-name-normalizer = { path = "politigraph-name-normalizer", editable = true }
poliquery = { path = "politigraph-poliquery", editable = true }
msbis-vote-events-scraper = { path = "politigraph_vote_events_scraper", editable = true }
lis-bills-scraper = { path = "politigraph-bills-scraper", editable = true }
merge-bill-updater = { path = "politigraph-merge-bill-detector", editable = true }
vote-doc-reader = { path = "vote-doc-reader", editable = true }
vote-log-manager = { path = "politigraph-votes-log", editable = true }
